name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH to server and trigger rebuild
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: raf-testnet.g9software.xyz 
          username: deploy
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
